Document: count-distinct
Title: Debian count-distinct Manual
Author: <insert document author here>
Abstract: This manual describes what count-distinct is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/count-distinct/count-distinct.sgml.gz

Format: postscript
Files: /usr/share/doc/count-distinct/count-distinct.ps.gz

Format: text
Files: /usr/share/doc/count-distinct/count-distinct.text.gz

Format: HTML
Index: /usr/share/doc/count-distinct/html/index.html
Files: /usr/share/doc/count-distinct/html/*.html
